### ISSUE TITLE
Allow Richel to modify the Settings of this repo

### ISSUE THREAD

**Issue by richelbilderbeek** [uppsala-makerspace/loerdagskurser#1]
Hi @Ramis84, 

For my own repos, I have the rights to modify the Settings of those repos:

![Screenshot from 2022-11-21 08-30-23](https://user-images.githubusercontent.com/2098230/202990779-db44320e-4833-486e-aa3f-c4ee5d574933.png)

For this repo, however, I do not have the rights to do so:

![Screenshot from 2022-11-21 08-30-10](https://user-images.githubusercontent.com/2098230/202990951-c4c6a239-a008-4ea4-8418-968c6389fc33.png)

Could you allow me to modify the settings of my repo?

Thanks and cheers, Richel

**Comment by Ramis84** [comment]
I have set you as admin on the repo. Please get back to me if you add more repos, since I may need to do this for each one.

**Comment by richelbilderbeek** [comment]
Thanks @Ramis84!
